#!/bin/sh

# shellcheck disable=SC2034
{
	set -a
	XDG_DATA_DIRS=/usr/share/xubuntu:/usr/share/xfce4:/usr/local/share:/usr/share
	XDG_CONFIG_DIRS=/etc/xdg/xdg-xubuntu:/etc/xdg
	XDG_CURRENT_DESKTOP=XFCE
	XDG_SESSION_DESKTOP=xubuntu
	XDG_SESSION_TYPE=x11
	XDG_MENU_PREFIX=xfce-
	XDG_DATA_HOME="${HOME:?}"/.local/share
	XDG_CONFIG_HOME="${HOME:?}"/.config
	XDG_CACHE_HOME="${HOME:?}"/.cache
	XDG_RUNTIME_DIR=/run/user/"$(id -u)"
	set +a
}
